const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

const time = new Date().getTime();
const xrw = 'X-Requested-With, content-type, Authorization';
let jsCompiler = false;
const { APP } = process.env;
let index = 'app';
if (APP) {
  index += `-${APP}`;
}
module.exports = require('./webpack.base.babel')({
  mode: 'development',
  jsCompiler,
  entry: [
    'webpack-hot-middleware/client?reload=true',
    path.join(process.cwd(), `app/${index}.js`), // Start with js/app.js
  ],
  // Don't use hashes in dev mode for better performance
  output: {
    filename: `[name]-time${time}.js`,
    chunkFilename: '[name].chunk.js',
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },
  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/index.html',
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',
  performance: {
    hints: false,
  },
  devServer: {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Headers': xrw,
    },
  },
});
